# Generated by Django 5.0.4 on 2026-05-06 20:46

import core.models.chapter
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SoundEffectCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="收藏集名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="收藏集描述"),
                ),
                (
                    "scene_type",
                    models.CharField(
                        blank=True,
                        help_text="如：武侠、仙侠、玄幻、都市",
                        max_length=50,
                        null=True,
                        verbose_name="场景类型",
                    ),
                ),
                (
                    "sound_count",
                    models.IntegerField(default=0, verbose_name="音效数量"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="公开收藏集"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="默认收藏集"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "音效收藏集",
                "verbose_name_plural": "音效收藏集",
                "db_table": "sound_effect_collections",
                "ordering": ["-is_default", "-sound_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="书名")),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="作者"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="书籍简介"),
                ),
                (
                    "language",
                    models.CharField(
                        default="zh-CN", max_length=50, verbose_name="语言"
                    ),
                ),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="封面图URL"
                    ),
                ),
                (
                    "cover_image_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="封面图存储路径",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=500, verbose_name="原始文件名"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="文件MD5哈希"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="MinIO存储路径",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待处理"),
                            ("ANALYZING", "正在分析"),
                            ("SYNTHESIZING", "正在合成"),
                            ("POST_PROCESSING", "正在后处理"),
                            ("PUBLISHING", "正在发布"),
                            ("DONE", "完成"),
                            ("FAILED", "失败"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("manual", "手动上传"), ("watch", "文件夹监听")],
                        default="manual",
                        max_length=20,
                        verbose_name="来源类型",
                    ),
                ),
                (
                    "total_chapters",
                    models.IntegerField(default=0, verbose_name="总章节数"),
                ),
                (
                    "processed_chapters",
                    models.IntegerField(default=0, verbose_name="已处理章节数"),
                ),
                (
                    "total_duration",
                    models.BigIntegerField(default=0, verbose_name="总音频时长"),
                ),
                (
                    "full_audio_path",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="完整有声书路径",
                    ),
                ),
                (
                    "full_audio_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="完整有声书时长"
                    ),
                ),
                (
                    "full_audio_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="完整有声书大小"
                    ),
                ),
                (
                    "full_audio_format",
                    models.CharField(
                        default="m4b", max_length=20, verbose_name="完整有声书格式"
                    ),
                ),
                (
                    "generation_mode",
                    models.CharField(
                        choices=[("auto", "自动模式"), ("manual", "手动模式")],
                        default="auto",
                        max_length=20,
                        verbose_name="生成模式",
                    ),
                ),
                (
                    "auto_publish_enabled",
                    models.BooleanField(default=False, verbose_name="启用自动发布"),
                ),
                (
                    "watch_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="监听路径"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "error_count",
                    models.IntegerField(default=0, verbose_name="错误重试次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="软删除时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "书籍",
                "verbose_name_plural": "书籍管理",
                "db_table": "books",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="books_status_f9c68b_idx"
                    ),
                    models.Index(
                        fields=["source_type", "status"],
                        name="books_source__b8f762_idx",
                    ),
                    models.Index(
                        fields=["deleted_at", "status"], name="books_deleted_814627_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_index", models.IntegerField(verbose_name="章节序号")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="章节标题"
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(blank=True, null=True, verbose_name="原始文本"),
                ),
                (
                    "cleaned_text",
                    models.TextField(blank=True, null=True, verbose_name="清洗后文本"),
                ),
                (
                    "analysis_result",
                    core.models.chapter.CompatibleJSONField(
                        blank=True, null=True, verbose_name="分析结果JSON"
                    ),
                ),
                (
                    "characters",
                    core.models.chapter.CompatibleJSONField(
                        blank=True, null=True, verbose_name="角色列表"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待处理"),
                            ("ANALYZING", "正在分析"),
                            ("ANALYZED", "已分析"),
                            ("SYNTHESIZING", "正在合成"),
                            ("AWAITING_CONFIRM", "等待确认"),
                            ("DONE", "完成"),
                            ("FAILED", "失败"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "next_chapter_id",
                    models.IntegerField(blank=True, null=True, verbose_name="下一章ID"),
                ),
                (
                    "audio_file_path",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="音频文件路径",
                    ),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="音频URL"
                    ),
                ),
                (
                    "audio_duration",
                    models.IntegerField(blank=True, null=True, verbose_name="音频时长"),
                ),
                (
                    "audio_file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="音频文件大小"
                    ),
                ),
                (
                    "audio_format",
                    models.CharField(
                        default="mp3", max_length=20, verbose_name="音频格式"
                    ),
                ),
                (
                    "subtitle_url",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="字幕URL"
                    ),
                ),
                (
                    "subtitle_path",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="字幕文件路径",
                    ),
                ),
                (
                    "total_segments",
                    models.IntegerField(default=0, verbose_name="总片段数"),
                ),
                (
                    "completed_segments",
                    models.IntegerField(default=0, verbose_name="已完成片段数"),
                ),
                (
                    "failed_segments",
                    models.IntegerField(default=0, verbose_name="失败片段数"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "deepseek_tokens",
                    models.IntegerField(default=0, verbose_name="DeepSeek消耗Token"),
                ),
                (
                    "minimax_characters",
                    models.IntegerField(default=0, verbose_name="MiniMax消耗字符"),
                ),
                (
                    "estimated_cost",
                    models.IntegerField(default=0, verbose_name="预估成本"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="core.book",
                        verbose_name="所属书籍",
                    ),
                ),
            ],
            options={
                "verbose_name": "章节",
                "verbose_name_plural": "章节管理",
                "db_table": "chapters",
                "ordering": ["chapter_index"],
            },
        ),
        migrations.CreateModel(
            name="AudioSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segment_index", models.IntegerField(verbose_name="片段序号")),
                ("text_content", models.TextField(verbose_name="文本内容")),
                (
                    "raw_text",
                    models.TextField(blank=True, null=True, verbose_name="原始文本"),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="角色名"
                    ),
                ),
                (
                    "emotion",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="情感标注"
                    ),
                ),
                (
                    "emotion_intensity",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="情感强度"
                    ),
                ),
                (
                    "speed",
                    models.CharField(
                        default="normal", max_length=20, verbose_name="语速"
                    ),
                ),
                (
                    "pause_after",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="段后停顿"
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="音色ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待处理"),
                            ("SYNTHESIZING", "正在合成"),
                            ("SUCCESS", "成功"),
                            ("FAILED", "失败"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "minimax_request_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="MiniMax请求ID",
                    ),
                ),
                (
                    "minimax_cost",
                    models.IntegerField(default=0, verbose_name="MiniMax消耗字符"),
                ),
                (
                    "deepseek_cost",
                    models.IntegerField(default=0, verbose_name="DeepSeek消耗Token"),
                ),
                (
                    "audio_file_path",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="音频文件路径",
                    ),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="音频URL"
                    ),
                ),
                (
                    "audio_duration_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="音频时长"),
                ),
                (
                    "audio_file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "extra_params",
                    models.JSONField(blank=True, null=True, verbose_name="额外参数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="core.chapter",
                        verbose_name="所属章节",
                    ),
                ),
            ],
            options={
                "verbose_name": "音频片段",
                "verbose_name_plural": "音频片段管理",
                "db_table": "audio_segments",
                "ordering": ["segment_index"],
            },
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paragraph_index", models.IntegerField(verbose_name="段落序号")),
                ("text", models.TextField(verbose_name="段落文本")),
                (
                    "paragraph_type",
                    models.CharField(
                        choices=[
                            ("narration", "旁白"),
                            ("dialogue", "对话"),
                            ("mixed", "混合"),
                        ],
                        default="narration",
                        max_length=20,
                        verbose_name="段落类型",
                    ),
                ),
                (
                    "speaker",
                    models.CharField(blank=True, max_length=100, verbose_name="说话人"),
                ),
                (
                    "is_narrator",
                    models.BooleanField(default=True, verbose_name="是否旁白"),
                ),
                (
                    "emotion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("calm", "平静"),
                            ("happy", "高兴"),
                            ("sad", "悲伤"),
                            ("angry", "愤怒"),
                            ("nervous", "紧张"),
                            ("surprised", "惊讶"),
                            ("gentle", "温柔"),
                            ("serious", "严肃"),
                            ("cold", "冷漠"),
                            ("sarcastic", "嘲讽"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="情感",
                    ),
                ),
                (
                    "emotion_intensity",
                    models.CharField(
                        blank=True,
                        choices=[("weak", "弱"), ("medium", "中"), ("strong", "强")],
                        max_length=20,
                        null=True,
                        verbose_name="情感强度",
                    ),
                ),
                (
                    "polyphone_fixes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="多音字修正"
                    ),
                ),
                (
                    "special_markers",
                    models.JSONField(blank=True, default=list, verbose_name="特殊标记"),
                ),
                (
                    "is_ancient_text",
                    models.BooleanField(default=False, verbose_name="古文"),
                ),
                ("is_poetry", models.BooleanField(default=False, verbose_name="诗词")),
                (
                    "is_inner_thought",
                    models.BooleanField(default=False, verbose_name="内心独白"),
                ),
                (
                    "is_system_prompt",
                    models.BooleanField(default=False, verbose_name="系统提示"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="core.chapter",
                        verbose_name="所属章节",
                    ),
                ),
            ],
            options={
                "verbose_name": "段落",
                "verbose_name_plural": "段落列表",
                "db_table": "paragraphs",
                "ordering": ["chapter", "paragraph_index"],
            },
        ),
        migrations.CreateModel(
            name="PublishChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="渠道名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="渠道描述"),
                ),
                (
                    "platform_type",
                    models.CharField(
                        choices=[
                            ("self_hosted", "自建平台"),
                            ("ximalaya", "喜马拉雅"),
                            ("qingting", "蜻蜓FM"),
                            ("lizhi", "荔枝FM"),
                            ("custom", "自定义平台"),
                        ],
                        default="self_hosted",
                        max_length=20,
                        verbose_name="平台类型",
                    ),
                ),
                (
                    "api_config",
                    models.JSONField(blank=True, null=True, verbose_name="API配置"),
                ),
                (
                    "oauth_client_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="OAuth客户端ID",
                    ),
                ),
                (
                    "oauth_access_token",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="OAuth访问令牌",
                    ),
                ),
                (
                    "oauth_refresh_token",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="OAuth刷新令牌",
                    ),
                ),
                (
                    "oauth_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="令牌过期时间"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "auto_publish",
                    models.BooleanField(default=False, verbose_name="是否自动发布"),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="发布优先级")),
                (
                    "publish_as_draft",
                    models.BooleanField(default=True, verbose_name="发布为草稿"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分类"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, null=True, verbose_name="标签列表"),
                ),
                (
                    "total_published",
                    models.IntegerField(default=0, verbose_name="已发布书籍数"),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="成功次数"),
                ),
                (
                    "failure_count",
                    models.IntegerField(default=0, verbose_name="失败次数"),
                ),
                (
                    "last_published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后发布时间"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="用户ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "发布渠道",
                "verbose_name_plural": "发布渠道管理",
                "db_table": "publish_channels",
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["platform_type", "is_enabled"],
                        name="publish_cha_platfor_a080e7_idx",
                    ),
                    models.Index(
                        fields=["user_id", "is_enabled"],
                        name="publish_cha_user_id_228b49_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PublishRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_album_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="外部专辑ID"
                    ),
                ),
                (
                    "external_album_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="外部专辑URL",
                    ),
                ),
                (
                    "external_category_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="外部分类ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待发布"),
                            ("preparing", "准备中"),
                            ("uploading", "上传中"),
                            ("done", "发布成功"),
                            ("failed", "发布失败"),
                            ("partially_done", "部分成功"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="发布状态",
                    ),
                ),
                (
                    "chapters_published",
                    models.JSONField(
                        blank=True, null=True, verbose_name="章节发布映射"
                    ),
                ),
                (
                    "total_chapters",
                    models.IntegerField(default=0, verbose_name="总章节数"),
                ),
                (
                    "published_chapters",
                    models.IntegerField(default=0, verbose_name="已发布章节数"),
                ),
                (
                    "failed_chapters",
                    models.IntegerField(default=0, verbose_name="失败章节数"),
                ),
                (
                    "api_calls",
                    models.IntegerField(default=0, verbose_name="API调用次数"),
                ),
                (
                    "estimated_cost",
                    models.IntegerField(default=0, verbose_name="预估成本"),
                ),
                (
                    "result_details",
                    models.JSONField(
                        blank=True, null=True, verbose_name="发布结果详情"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="错误代码"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Celery任务ID",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_records",
                        to="core.book",
                        verbose_name="所属书籍",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_records",
                        to="core.publishchannel",
                        verbose_name="发布渠道",
                    ),
                ),
            ],
            options={
                "verbose_name": "发布记录",
                "verbose_name_plural": "发布记录管理",
                "db_table": "publish_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SoundEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="音效名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="音效描述"),
                ),
                (
                    "chinese_description",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="中文描述"
                    ),
                ),
                (
                    "effect_type",
                    models.CharField(
                        choices=[
                            ("environment", "环境音"),
                            ("action", "动作音"),
                            ("transition", "转场音"),
                            ("nature", "自然音"),
                            ("ambient", "氛围音"),
                            ("weather", "天气音"),
                            ("urban", "城市音"),
                            ("fantasy", "玄幻/奇幻音"),
                            ("scifi", "科幻音"),
                        ],
                        db_index=True,
                        default="environment",
                        max_length=20,
                        verbose_name="音效类型",
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("foreground", "前景音效"),
                            ("background", "背景音效"),
                        ],
                        default="foreground",
                        max_length=20,
                        verbose_name="音效层级",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        help_text="如：['rain', 'heavy', 'outdoor', 'night']",
                        null=True,
                        verbose_name="标签列表",
                    ),
                ),
                (
                    "chinese_tags",
                    models.JSONField(
                        blank=True,
                        help_text="如：['雨声', '大雨', '户外', '夜晚']",
                        null=True,
                        verbose_name="中文标签",
                    ),
                ),
                (
                    "semantic_keywords",
                    models.JSONField(
                        blank=True,
                        help_text="用于语义搜索的关键词列表",
                        null=True,
                        verbose_name="语义关键词",
                    ),
                ),
                (
                    "audio_embedding",
                    models.JSONField(
                        blank=True, null=True, verbose_name="音频特征向量"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("bbc", "BBC Sound Effects"),
                            ("fsd50k", "FSD50K"),
                            ("user_upload", "用户上传"),
                            ("generated", "AI生成"),
                        ],
                        default="bbc",
                        max_length=20,
                        verbose_name="音效来源",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        help_text="BBC Sound Effects 的资源ID",
                        max_length=255,
                        null=True,
                        verbose_name="来源ID",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="原始URL"
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        blank=True,
                        help_text="如：BBC License, CC0, Creative Commons",
                        max_length=100,
                        null=True,
                        verbose_name="许可证类型",
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="时长(毫秒)"
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="文件格式"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "sample_rate",
                    models.IntegerField(blank=True, null=True, verbose_name="采样率"),
                ),
                (
                    "local_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="本地存储路径",
                    ),
                ),
                (
                    "minio_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="MinIO存储路径",
                    ),
                ),
                (
                    "minio_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="MinIO访问URL",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "可用"),
                            ("downloading", "下载中"),
                            ("unavailable", "不可用"),
                            ("archived", "已归档"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="收藏"),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="使用次数"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "高优先级"),
                            ("medium", "中优先级"),
                            ("low", "低优先级"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="推荐优先级",
                    ),
                ),
                (
                    "suitable_scenes",
                    models.JSONField(
                        blank=True,
                        help_text="如：['武侠', '仙侠', '都市', '玄幻']",
                        null=True,
                        verbose_name="适用场景",
                    ),
                ),
                (
                    "recommended_volume_min",
                    models.FloatField(
                        blank=True, null=True, verbose_name="推荐音量下限"
                    ),
                ),
                (
                    "recommended_volume_max",
                    models.FloatField(
                        blank=True, null=True, verbose_name="推荐音量上限"
                    ),
                ),
                (
                    "recommended_fade_in_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="推荐淡入时间(ms)"
                    ),
                ),
                (
                    "recommended_fade_out_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="推荐淡出时间(ms)"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="已审核"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后使用时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "音效",
                "verbose_name_plural": "音效库",
                "db_table": "sound_effects",
                "ordering": ["-usage_count", "-priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["effect_type", "status"],
                        name="sound_effec_effect__380e9f_idx",
                    ),
                    models.Index(
                        fields=["source", "status"],
                        name="sound_effec_source_b8dfcf_idx",
                    ),
                    models.Index(
                        fields=["-usage_count"], name="sound_effec_usage_c_446848_idx"
                    ),
                    models.Index(
                        fields=["-priority"], name="sound_effec_priorit_b1509d_idx"
                    ),
                    models.Index(
                        fields=["is_verified", "status"],
                        name="sound_effec_is_veri_8bf058_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SoundEffectCollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_volume",
                    models.FloatField(blank=True, null=True, verbose_name="自定义音量"),
                ),
                (
                    "custom_fade_in_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="自定义淡入时间"
                    ),
                ),
                (
                    "custom_fade_out_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="自定义淡出时间"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序顺序")),
                (
                    "added_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="添加时间"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.soundeffectcollection",
                        verbose_name="收藏集",
                    ),
                ),
                (
                    "sound_effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to="core.soundeffect",
                        verbose_name="音效",
                    ),
                ),
            ],
            options={
                "verbose_name": "音效收藏集项目",
                "verbose_name_plural": "音效收藏集项目",
                "db_table": "sound_effect_collection_items",
                "ordering": ["sort_order", "added_at"],
            },
        ),
        migrations.AddField(
            model_name="soundeffectcollection",
            name="sound_effects",
            field=models.ManyToManyField(
                related_name="collections",
                through="core.SoundEffectCollectionItem",
                to="core.soundeffect",
                verbose_name="音效列表",
            ),
        ),
        migrations.CreateModel(
            name="SoundEffectUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_id",
                    models.IntegerField(blank=True, null=True, verbose_name="书籍ID"),
                ),
                (
                    "chapter_id",
                    models.IntegerField(blank=True, null=True, verbose_name="章节ID"),
                ),
                (
                    "trigger_at_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="触发时间(ms)"
                    ),
                ),
                (
                    "volume",
                    models.FloatField(blank=True, null=True, verbose_name="音量"),
                ),
                (
                    "fade_in_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="淡入时间(ms)"
                    ),
                ),
                (
                    "fade_out_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="淡出时间(ms)"
                    ),
                ),
                ("loop", models.BooleanField(default=False, verbose_name="是否循环")),
                (
                    "matched_from_query",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="匹配查询"
                    ),
                ),
                (
                    "match_score",
                    models.FloatField(blank=True, null=True, verbose_name="匹配分数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="使用时间"
                    ),
                ),
                (
                    "sound_effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="core.soundeffect",
                        verbose_name="音效",
                    ),
                ),
            ],
            options={
                "verbose_name": "音效使用记录",
                "verbose_name_plural": "音效使用记录",
                "db_table": "sound_effect_usages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TTSTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Celery任务ID",
                    ),
                ),
                (
                    "parent_task_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="父任务ID"
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        default="full", max_length=50, verbose_name="任务类型"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待执行"),
                            ("analyzing", "正在分析"),
                            ("synthesizing", "正在合成"),
                            ("post_processing", "正在后处理"),
                            ("publishing", "正在发布"),
                            ("done", "完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "total_segments",
                    models.IntegerField(default=0, verbose_name="总片段数"),
                ),
                (
                    "completed_segments",
                    models.IntegerField(default=0, verbose_name="已完成片段数"),
                ),
                (
                    "failed_segments",
                    models.IntegerField(default=0, verbose_name="失败片段数"),
                ),
                (
                    "deepseek_total_tokens",
                    models.IntegerField(default=0, verbose_name="DeepSeek总消耗Token"),
                ),
                (
                    "minimax_total_characters",
                    models.IntegerField(default=0, verbose_name="MiniMax总消耗字符"),
                ),
                (
                    "total_cost_estimate",
                    models.IntegerField(default=0, verbose_name="总预估成本"),
                ),
                (
                    "deepseek_calls",
                    models.IntegerField(default=0, verbose_name="DeepSeek调用次数"),
                ),
                (
                    "deepseek_avg_latency_ms",
                    models.IntegerField(default=0, verbose_name="DeepSeek平均延迟"),
                ),
                (
                    "minimax_calls",
                    models.IntegerField(default=0, verbose_name="MiniMax调用次数"),
                ),
                (
                    "minimax_avg_latency_ms",
                    models.IntegerField(default=0, verbose_name="MiniMax平均延迟"),
                ),
                (
                    "total_audio_duration_ms",
                    models.BigIntegerField(default=0, verbose_name="总音频时长"),
                ),
                (
                    "output_format",
                    models.CharField(
                        default="mp3", max_length=20, verbose_name="输出格式"
                    ),
                ),
                (
                    "worker_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="执行Worker"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="任务开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="任务完成时间"
                    ),
                ),
                (
                    "estimated_remaining_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="预估剩余时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "error_traceback",
                    models.TextField(blank=True, null=True, verbose_name="错误堆栈"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tts_task",
                        to="core.book",
                        verbose_name="所属书籍",
                    ),
                ),
            ],
            options={
                "verbose_name": "TTS任务",
                "verbose_name_plural": "TTS任务管理",
                "db_table": "tts_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="音色名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="音色描述"),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("narrator", "旁白"),
                            ("male_lead", "男主角"),
                            ("female_lead", "女主角"),
                            ("elderly", "老人"),
                            ("child", "儿童"),
                            ("villain", "反派"),
                            ("supporting", "配角"),
                            ("custom", "自定义"),
                        ],
                        default="narrator",
                        max_length=20,
                        verbose_name="角色类型",
                    ),
                ),
                (
                    "character_names",
                    models.JSONField(
                        blank=True, null=True, verbose_name="关联的角色名称"
                    ),
                ),
                (
                    "minimax_voice_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="MiniMax音色ID",
                    ),
                ),
                (
                    "minimax_model",
                    models.CharField(
                        default="speech-01-turbo",
                        max_length=50,
                        verbose_name="MiniMax模型",
                    ),
                ),
                ("speed", models.FloatField(default=1.0, verbose_name="语速倍率")),
                ("pitch", models.FloatField(default=0.0, verbose_name="音调")),
                ("volume", models.FloatField(default=1.0, verbose_name="音量")),
                (
                    "emotion_params",
                    models.JSONField(blank=True, null=True, verbose_name="情感参数"),
                ),
                (
                    "is_system_preset",
                    models.BooleanField(default=False, verbose_name="是否系统预设"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="创建者"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序顺序")),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="使用次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_profiles",
                        to="core.book",
                        verbose_name="所属书籍",
                    ),
                ),
            ],
            options={
                "verbose_name": "音色配置",
                "verbose_name_plural": "音色配置管理",
                "db_table": "voice_profiles",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="角色名称")),
                (
                    "aliases",
                    models.JSONField(blank=True, default=list, verbose_name="别名列表"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女"), ("unknown", "未知")],
                        default="unknown",
                        max_length=20,
                        verbose_name="性别",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("protagonist", "主角"),
                            ("supporting", "配角"),
                            ("minor", "龙套"),
                            ("narrator", "旁白"),
                        ],
                        default="supporting",
                        max_length=20,
                        verbose_name="角色类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="角色描述")),
                ("personality", models.TextField(blank=True, verbose_name="性格特征")),
                ("speech_style", models.TextField(blank=True, verbose_name="说话风格")),
                (
                    "voice_description",
                    models.TextField(blank=True, verbose_name="声音描述"),
                ),
                (
                    "emotions",
                    models.JSONField(blank=True, default=list, verbose_name="常用情感"),
                ),
                (
                    "dialogue_count",
                    models.IntegerField(default=0, verbose_name="对话数量"),
                ),
                (
                    "appears_in_chapters",
                    models.JSONField(
                        blank=True, default=list, verbose_name="出现章节序号"
                    ),
                ),
                (
                    "voice_prompt",
                    models.TextField(blank=True, verbose_name="语音提示词"),
                ),
                (
                    "custom_voice_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="自定义语音ID"
                    ),
                ),
                (
                    "custom_speed",
                    models.FloatField(default=1.0, verbose_name="语速调整"),
                ),
                (
                    "custom_pitch",
                    models.FloatField(default=0.0, verbose_name="音调调整"),
                ),
                (
                    "custom_volume",
                    models.FloatField(default=1.0, verbose_name="音量调整"),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=50, verbose_name="来源"),
                ),
                (
                    "minio_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="MinIO存储路径"
                    ),
                ),
                (
                    "minio_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="MinIO URL"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("inactive", "未激活"),
                            ("archived", "已归档"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="core.book",
                        verbose_name="所属书籍",
                    ),
                ),
                (
                    "voice_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="characters",
                        to="core.voiceprofile",
                        verbose_name="关联语音",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色列表",
                "db_table": "characters",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["book", "chapter_index"], name="chapters_book_id_6f255a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["book", "status"], name="chapters_book_id_772e65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(fields=["status"], name="ix_chapters_status"),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(
                fields=("book", "chapter_index"), name="uq_book_chapter"
            ),
        ),
        migrations.AddIndex(
            model_name="audiosegment",
            index=models.Index(
                fields=["chapter", "segment_index"],
                name="audio_segme_chapter_1184ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audiosegment",
            index=models.Index(
                fields=["chapter", "status"], name="audio_segme_chapter_3fb89c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiosegment",
            index=models.Index(fields=["status"], name="ix_segments_status"),
        ),
        migrations.AddConstraint(
            model_name="audiosegment",
            constraint=models.UniqueConstraint(
                fields=("chapter", "segment_index"), name="uq_chapter_segment"
            ),
        ),
        migrations.AddIndex(
            model_name="paragraph",
            index=models.Index(
                fields=["chapter", "paragraph_index"],
                name="paragraphs_chapter_ecead0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paragraph",
            index=models.Index(
                fields=["paragraph_type"], name="paragraphs_paragra_06092d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paragraph",
            index=models.Index(
                fields=["emotion"], name="paragraphs_emotion_3266ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paragraph",
            index=models.Index(
                fields=["speaker"], name="paragraphs_speaker_5af29b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paragraph",
            constraint=models.UniqueConstraint(
                fields=("chapter", "paragraph_index"), name="uq_chapter_paragraph"
            ),
        ),
        migrations.AddIndex(
            model_name="publishrecord",
            index=models.Index(
                fields=["book", "channel"], name="publish_rec_book_id_3077fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publishrecord",
            index=models.Index(
                fields=["status", "created_at"], name="publish_rec_status_aeaaf3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="publishrecord",
            constraint=models.UniqueConstraint(
                fields=("book", "channel"), name="uq_book_channel"
            ),
        ),
        migrations.AddConstraint(
            model_name="soundeffectcollectionitem",
            constraint=models.UniqueConstraint(
                fields=("collection", "sound_effect"), name="uq_collection_sound_effect"
            ),
        ),
        migrations.AddIndex(
            model_name="soundeffectusage",
            index=models.Index(
                fields=["sound_effect", "created_at"],
                name="sound_effec_sound_e_466a9c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="soundeffectusage",
            index=models.Index(
                fields=["book_id", "chapter_id"], name="sound_effec_book_id_f72625_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ttstask",
            index=models.Index(
                fields=["status", "created_at"], name="tts_tasks_status_e662a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voiceprofile",
            index=models.Index(
                fields=["book", "role_type"], name="voice_profi_book_id_9e670e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                fields=["book", "name"], name="characters_book_id_db0e1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(fields=["status"], name="characters_status_96e1e1_idx"),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                fields=["role_type"], name="characters_role_ty_5731e8_idx"
            ),
        ),
    ]
